#!/bin/bash

tyrellCorpIP="192.168.1.134"
deckardIP="192.168.1.242"
jfsebastianIP="192.168.1.99"
off_worldIP="94.237.93.110"
voight_kampffIP="192.168.2.120"
hogwartsIP="192.168.2.82"

alias tyrellCorp="ssh $USER@$tyrellCorpIP"
alias deckard="ssh $USER@$deckardIP"
alias jfsebastian="ssh $USER@$jfsebastianIP"
alias off-world="ssh $USER@$off_worldIP"
alias voight-kampff="ssh $USER@$voight_kampffIP"
alias hogwarts="ssh $USER@$hogwartsIP"
